'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {Database}=require('../src/database');const {BotEngine}=require('../src/bot-engine');const {classifyTriggerPolicy}=require('../src/trigger-policy');const {runtimeCompatibility}=require('../src/runtime-compatibility');const {loadCorpus,summarize}=require('../src/corpus-runner');
function holder(seed=true){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hub-v0150-'));const file=path.join(dir,'hub.sqlite');const db=new Database(file,{seedBundledContent:seed});db.setSettings({cooldown_seconds:'0',private_context_without_reply:'true',persistent_context_enabled:'true'});return{dir,file,db,close(){db.close();fs.rmSync(dir,{recursive:true,force:true});}};}
function msg(body,replies,user='5577999999999@s.whatsapp.net'){return{fromMe:false,from:user,author:user,body,senderName:'Teste',timestampMs:Date.now(),quotedFromMe:false,mentionedMe:false,async getChat(){return{isGroup:false,id:{_serialized:user},name:'Teste'};},async sendResponse(payload){replies.push(String(payload.text||''));return{key:{id:`r-${replies.length}`}};}};}
test('migração 0150 é versionada, transacional e idempotente',()=>{const h=holder(false);try{const rows=h.db.listSchemaMigrations();assert.ok(rows.some(row=>row.migration_id==='0150-architecture'));assert.match(rows.find(row=>row.migration_id==='0150-architecture').checksum,/^[a-f0-9]{64}$/u);assert.deepEqual(h.db.runVersionedMigrations(),[]);}finally{h.close();}});
test('quadro estruturado é a fonte da resposta por semestre',()=>{const h=holder(true);const engine=new BotEngine(h.db);try{const entry=h.db.listProfessorScheduleEntries({academicPeriod:'2026.2',discipline:'LPI'})[0];assert.ok(entry);h.db.saveProfessorScheduleEntry({...entry,room:'TESTE-0150'},entry.id);const result=engine.simulate('semestre 2',{isGroup:false,ignorePermissions:true});assert.match(result.text,/TESTE-0150/u);assert.doesNotMatch(result.text,/Sala: H008/u);}finally{engine.close();h.close();}});
test('contexto curto persiste após reinício do motor',async()=>{const h=holder(true);let engine=new BotEngine(h.db);const replies=[];try{await engine.handle(msg('qual sala de LPI?',replies));engine.close();engine=new BotEngine(h.db);await engine.handle(msg('e o horário?',replies));assert.equal(replies.length,2);assert.match(replies[1],/Horário/u);assert.match(replies[1],/LPI/u);}finally{engine.close();h.close();}});
test('modo de observação registra sem responder',async()=>{const h=holder(true);const engine=new BotEngine(h.db);try{const created=h.db.saveAutomaticMessage({title:'Observação 0150',response_text:'Não deveria sair',trigger:{sentences:['frase observada exclusiva 0150']},active:true});h.db.setAutomaticMessageObservationMode(created.id,true);await engine.reloadRules('test');const result=engine.evaluate('frase observada exclusiva 0150',{isGroup:false,ignorePermissions:true});assert.equal(result.matched,false);assert.equal(h.db.listTriggerObservations().length,1);}finally{engine.close();h.close();}});
test('relatos de falso positivo e validade acadêmica ficam disponíveis',()=>{const h=holder(true);try{const id=h.db.addFalsePositiveReport({original_message:'teste',feedback_text:'não era isso',matched_title:'Card'});assert.ok(id);assert.equal(h.db.listFalsePositiveReports().length,1);const status=h.db.academicDataStatus();assert.equal(status.academic_period,'2026.2');assert.ok(Number(status.latest?.entry_count||0)>0);}finally{h.close();}});
test('política, corpus e runtime possuem contratos estáveis',()=>{assert.equal(classifyTriggerPolicy({title:'Professor — Teste',trigger:{sentences:['teste']}}).category,'entity');assert.ok(loadCorpus().length>=10);assert.deepEqual(summarize([{response_correct:true,expected_respond:true,actual_respond:true}]).failed,0);assert.equal(runtimeCompatibility('22.13.0').supported,true);assert.equal(runtimeCompatibility('23.0.0').supported,false);});
test('manifesto e release não incluem conteúdo privado',()=>{const root=path.resolve(__dirname,'..');const script=fs.readFileSync(path.join(root,'scripts','build-update-manifest.js'),'utf8');assert.match(script,/private-content\.json/u);const lock=JSON.parse(fs.readFileSync(path.join(root,'package-lock.json'),'utf8'));assert.equal(lock.packages[''].engines.node,'>=22.13 <23');});
